# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import duplicatedlog_pb2 as duplicatedlog__pb2


class ProtocolStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.register_secondary_node = channel.unary_unary(
                '/duplicatedlog.Protocol/register_secondary_node',
                request_serializer=duplicatedlog__pb2.Request.SerializeToString,
                response_deserializer=duplicatedlog__pb2.Response.FromString,
                )
        self.replicate = channel.unary_unary(
                '/duplicatedlog.Protocol/replicate',
                request_serializer=duplicatedlog__pb2.Request.SerializeToString,
                response_deserializer=duplicatedlog__pb2.Response.FromString,
                )


class ProtocolServicer(object):
    """Missing associated documentation comment in .proto file."""

    def register_secondary_node(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def replicate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProtocolServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'register_secondary_node': grpc.unary_unary_rpc_method_handler(
                    servicer.register_secondary_node,
                    request_deserializer=duplicatedlog__pb2.Request.FromString,
                    response_serializer=duplicatedlog__pb2.Response.SerializeToString,
            ),
            'replicate': grpc.unary_unary_rpc_method_handler(
                    servicer.replicate,
                    request_deserializer=duplicatedlog__pb2.Request.FromString,
                    response_serializer=duplicatedlog__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'duplicatedlog.Protocol', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Protocol(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def register_secondary_node(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/duplicatedlog.Protocol/register_secondary_node',
            duplicatedlog__pb2.Request.SerializeToString,
            duplicatedlog__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def replicate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/duplicatedlog.Protocol/replicate',
            duplicatedlog__pb2.Request.SerializeToString,
            duplicatedlog__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
